#!/usr/bin/env bash
# Downloads test fixtures for StringArt.jl. Idempotent — skips existing files.
# All sources are public domain or permissively licensed. See LICENSES.md.
#
# Usage: bash test/fixtures/fetch.sh
# Requires: curl. Optional: ImageMagick (`convert`) for square-crop step.

set -euo pipefail

DIR="$(dirname -- "$(realpath -- "${BASH_SOURCE[0]}")")"
UA="StringArt.jl-fixtures/1.0 (https://github.com/neumann-mlucas/StringArt.jl)"

fetch() {
  local out="$1" url="$2"
  if [[ -s "$DIR/$out" ]]; then
    echo "skip  $out (exists)"
    return
  fi
  echo "get   $out"
  curl -fsSL -A "$UA" -o "$DIR/$out.part" "$url"
  mv "$DIR/$out.part" "$DIR/$out"
}

# --- Wikimedia Commons (public domain) — 1280px thumbs -----------------------
WM="https://upload.wikimedia.org/wikipedia/commons/thumb"

fetch girl_pearl.jpg    "$WM/0/0f/1665_Girl_with_a_Pearl_Earring.jpg/1280px-1665_Girl_with_a_Pearl_Earring.jpg"
fetch mona_lisa.jpg     "$WM/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/1280px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg"
fetch great_wave.jpg    "$WM/a/a5/Tsunami_by_hokusai_19th_century.jpg/1280px-Tsunami_by_hokusai_19th_century.jpg"
fetch starry_night.jpg  "$WM/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg"
fetch van_gogh_self.jpg "$WM/b/b2/Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg/1280px-Vincent_van_Gogh_-_Self-Portrait_-_Google_Art_Project.jpg"

# --- Wikimedia Commons (CC BY-SA 3.0 — attribution required, see LICENSES) ---
fetch moon.jpg          "$WM/e/e1/FullMoon2010.jpg/1280px-FullMoon2010.jpg"

# --- Kodak True Color suite (Kodak permissive) -------------------------------
KODAK="https://r0k.us/graphics/kodak/kodak"
fetch parrots.png       "$KODAK/kodim23.png"
fetch flowers.png       "$KODAK/kodim07.png"
fetch hats.png          "$KODAK/kodim04.png"

# --- USC-SIPI (research use) -------------------------------------------------
fetch mandrill.tiff     "https://sipi.usc.edu/database/download.php?vol=misc&img=4.2.03"

echo
echo "done. see LICENSES.md for attribution requirements."
echo "synthetic fixtures (checker, gradient, text, radial) are generated by the test harness."
